[manifest]
version = "1.0.0"
priority = 0

# G.FUNCS.use_card: if the button is star_select_consumeable, select it to G.consumeables
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "e.config.button = nil"
position = "before"
match_indent = true
payload = "local button = e.config.button"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
localize{type = 'unlocks', key = res.key or _c.key, set = res.set or _c.set, nodes = desc_nodes, vars = loc_vars, text_colour = res.text_colour, scale = res.scale}
'''
position = "at"
payload = '''
if _c.rarity and _c.rarity == 'star_galaxy' and specific_vars and not specific_vars.not_hidden then 
    localize{type = 'unlocks', key = res.key or 'joker_locked_galaxy', set = res.set or 'Other', nodes = desc_nodes, vars = loc_vars, text_colour = res.text_colour, scale = res.scale}
else
localize{type = 'unlocks', key = res.key or _c.key, set = res.set or _c.set, nodes = desc_nodes, vars = loc_vars, text_colour = res.text_colour, scale = res.scale}
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "local select_to = card.area == G.pack_cards and G.pack_cards and booster_obj and SMODS.card_select_area(card, booster_obj) and card:selectable_from_pack(booster_obj)"
position = "after"
match_indent = true
payload = "if button == 'star_select_consumeable' then select_to = 'consumeables' end"

# create_card: if Heist has been redeemed, increase the odds of hidden consumables appearing
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not forced_key and soulable and (not G.GAME.banned_keys['c_soul']) then"
position = "after"
match_indent = true
payload = "    local multiplier = next(SMODS.find_card('v_star_heist')) and 5 or 1"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if pseudorandom('soul_'..v.key.._type..G.GAME.round_resets.ante) > (1 - v.soul_rate) then"
position = "at"
match_indent = true
payload = "if pseudorandom('soul_'..v.key.._type..G.GAME.round_resets.ante) > (1 - (v.soul_rate * multiplier)) then"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > 0.997 then"
position = "at"
match_indent = true
payload = "if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > (1 - (0.003 * multiplier)) then"